# Generated by Django 5.0.1 on 2024-02-08 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avr_type', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartrelay',
            name='model',
            field=models.CharField(choices=[('ПР200', 'Pr200'), ('ПР205', 'Pr205'), ('ПР103', 'Pr103'), ('SR3B261BD', 'Sr3B261Bd'), ('SR2B261FU', 'Sr2B261Fu'), ('SR2B201FU', 'Sr2B201Fu'), ('SR2B121FU', 'Sr2B121Fu'), ('Oni', 'Oni'), ('LOGO!8', 'Logo')], max_length=20, verbose_name='Модель'),
        ),
    ]
