# Generated by Django 5.0.1 on 2024-02-08 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avr_type', '0002_alter_smartrelay_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='classification',
            name='slug',
            field=models.SlugField(default=11, max_length=120, verbose_name='URL'),
            preserve_default=False,
        ),
    ]
