# Generated by Django 5.0.1 on 2024-02-08 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avr_type', '0003_classification_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='classification',
            name='access',
            field=models.BooleanField(default=True),
        ),
    ]
