# Generated by Django 5.0.1 on 2024-02-08 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avr_type', '0004_classification_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeavr',
            name='access',
            field=models.BooleanField(default=True, verbose_name='Доступ'),
        ),
        migrations.AlterField(
            model_name='classification',
            name='access',
            field=models.BooleanField(default=True, verbose_name='Доступ'),
        ),
    ]
