# Generated by Django 5.0.1 on 2024-02-15 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avr_type', '0005_typeavr_access_alter_classification_access'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
                ('description', models.TextField(verbose_name='Описание')),
                ('link', models.URLField(verbose_name='Ссылка на систему')),
                ('is_active', models.BooleanField(default=False, verbose_name='Модерация')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
        ),
    ]
