# Generated by Django 5.0.1 on 2024-02-15 08:19

import avr_type.models
import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avr_type', '0006_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='photo',
            field=imagekit.models.fields.ProcessedImageField(default=1, upload_to=avr_type.models.banner_images_directory_path, verbose_name='Основное фото'),
            preserve_default=False,
        ),
    ]
