# Generated by Django 5.0.1 on 2024-02-16 09:23

import avr_type.models
import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avr_type', '0008_imagetypeavr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetypeavr',
            name='photo',
            field=imagekit.models.fields.ProcessedImageField(upload_to=avr_type.models.system_images_directory_path, verbose_name='Основное фото'),
        ),
    ]
