# Generated by Django 5.0.1 on 2024-02-19 01:20

import avr_type.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avr_type', '0009_alter_imagetypeavr_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetypeavr',
            name='photo',
            field=models.ImageField(upload_to=avr_type.models.system_images_directory_path, verbose_name='Основное фото'),
        ),
    ]
