# Generated by Django 5.0.1 on 2024-02-19 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avr_type', '0011_advantage'),
    ]

    operations = [
        migrations.AddField(
            model_name='advantage',
            name='access',
            field=models.BooleanField(default=True, verbose_name='Доступ'),
        ),
    ]
