# Generated by Django 5.0.1 on 2024-02-19 07:39

import avr_type.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avr_type', '0012_advantage_access'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classification',
            old_name='shoice_in',
            new_name='choice_in',
        ),
        migrations.RenameField(
            model_name='smartrelay',
            old_name='brend',
            new_name='brand',
        ),
        migrations.AlterField(
            model_name='advantage',
            name='icon',
            field=models.ImageField(upload_to=avr_type.models.advantage_icon_directory_path, verbose_name='Икоонка'),
        ),
    ]
