# Generated by Django 5.0.1 on 2024-03-06 04:07

import avr_type.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avr_type', '0013_rename_shoice_in_classification_choice_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classification',
            name='macro_code',
            field=models.CharField(default=0, max_length=12, verbose_name='Код к макросам'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advantage',
            name='icon',
            field=models.ImageField(upload_to=avr_type.models.advantage_icon_directory_path, verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='classification',
            name='work_tp',
            field=models.BooleanField(default=True, verbose_name='Режим работы тр-ров'),
        ),
        migrations.AlterField(
            model_name='file',
            name='firmware',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='avr_type.classification', verbose_name='Алгоритм'),
        ),
    ]
