# Generated by Django 5.0.1 on 2024-03-18 09:15

import avr_type.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avr_type', '0014_classification_macro_code_alter_advantage_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='scheme',
            field=models.FileField(default=1, upload_to=avr_type.models.path_order_file_scheme, verbose_name='Схема АВР'),
            preserve_default=False,
        ),
    ]
