# Generated by Django 5.0.1 on 2024-03-18 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avr_type', '0015_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='access',
            field=models.BooleanField(default=False, verbose_name='Архив'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('В обработке', 'Process'), ('Заказано', 'Ordered'), ('Готов', 'Ready'), ('В работе', 'Work')], max_length=15, verbose_name='Статус заказа'),
        ),
    ]
