# Generated by Django 5.0.1 on 2024-03-19 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avr_type', '0016_alter_classification_access'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advantage',
            options={'verbose_name': 'преимущество', 'verbose_name_plural': 'преимущества'},
        ),
        migrations.AlterModelOptions(
            name='classification',
            options={'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
        migrations.AlterModelOptions(
            name='file',
            options={'verbose_name': 'файл', 'verbose_name_plural': 'файлы'},
        ),
        migrations.AlterModelOptions(
            name='imagetypeavr',
            options={'verbose_name': 'картинка', 'verbose_name_plural': 'картинки'},
        ),
        migrations.AlterModelOptions(
            name='smartrelay',
            options={'verbose_name': 'плк', 'verbose_name_plural': 'плк'},
        ),
        migrations.AlterModelOptions(
            name='typeavr',
            options={'verbose_name': 'система', 'verbose_name_plural': 'системы'},
        ),
    ]
