# Generated by Django 5.0.1 on 2024-03-20 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avr_type', '0017_alter_advantage_options_alter_classification_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='work_tp',
            field=models.BooleanField(default=False, verbose_name='Работа тр-ров (параллель)'),
        ),
    ]
