# Generated by Django 5.0.1 on 2024-03-20 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avr_type', '0018_alter_classification_work_tp'),
    ]

    operations = [
        migrations.AddField(
            model_name='classification',
            name='sell',
            field=models.BooleanField(default=True, verbose_name='Доступ'),
        ),
    ]
