# Generated by Django 5.0.1 on 2024-03-20 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avr_type', '0019_classification_sell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='access',
            field=models.BooleanField(default=False, verbose_name='Свободно'),
        ),
        migrations.AlterField(
            model_name='classification',
            name='sell',
            field=models.BooleanField(default=True, verbose_name='Продажа'),
        ),
    ]
