# Generated by Django 5.0.1 on 2024-03-21 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avr_type', '0020_alter_classification_access_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='macro_code',
            field=models.CharField(blank=True, default='', max_length=12, verbose_name='Код к макросам'),
        ),
    ]
