# Generated by Django 5.0.1 on 2024-03-21 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avr_type', '0021_alter_classification_macro_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartrelay',
            name='access',
            field=models.BooleanField(default=True, verbose_name='Доступ'),
        ),
    ]
