# Generated by Django 5.0.1 on 2024-03-25 02:33

import django.db.models.deletion
import software.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SoftWare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('slug', models.SlugField(max_length=100, verbose_name='URL')),
                ('access', models.BooleanField(default=True, verbose_name='Доступ')),
            ],
            options={
                'verbose_name': 'сервис',
                'verbose_name_plural': 'сервисы',
                'db_table': 'software',
            },
        ),
        migrations.CreateModel(
            name='FileSoftware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_service', models.FileField(upload_to=software.models.path_file_service, verbose_name='Файл ПО')),
                ('file_driver', models.FileField(upload_to=software.models.path_file_driver, verbose_name='Драйвер')),
                ('file_instruction', models.FileField(upload_to=software.models.path_file_instruction, verbose_name='Инструкция')),
                ('software', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='software.software', verbose_name='Сервисное ПО')),
            ],
            options={
                'verbose_name': 'файл',
                'verbose_name_plural': 'файлы',
                'db_table': 'filesoftware',
            },
        ),
    ]
