# Generated by Django 5.0.1 on 2024-03-25 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0002_alter_filesoftware_file_driver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='description',
            field=models.TextField(default=1, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filesoftware',
            name='software',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='softwares', to='software.software', verbose_name='Сервисное ПО'),
        ),
    ]
